server:
  port: 8080

security:
  authType: "jwt"
  jwt:
    secretKey: "PUT_SECRET_KEY"
    expirationTime: 3600000

logging:
  level:
    root: info

# Increased timeout to fit slower environments like TravisCI
spring:
  couchbase:
    env:
      timeouts:
        view: 15000
        query: 15000
    connection-string: "couchbase://127.0.0.1"
    username: "Administrator"
    password: "password"
  data:
    couchbase:
      bucket-name: "auth"
      auto-index: true